##################################################
# CONFIGURATION FILE FOR LUNG METAG MICROBIOME #
##################################################

techpar:
  threads: 12

input:
  dir_rawdata: "/net/data.isilon/ag-saez/bq_shared/promise_lung_microbiome_raw"
  # input folder for all the other databases
  dir_input: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/input"
  adapters: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/input/adapt.fas"
  multiqc_config: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/workflow/config/multiqc_config.yaml"

output:
  dir_out : "/net/bq-storage/ag-jaeger-partner/output/metaG_output"

samples:
  # unique sample IDs
  allSamplesUnique: "/net/data.isilon/ag-saez/bq_shared/promise_lung_microbiome_raw/AAC5HN3HV_Promise_Batch03_23s002468*"

DB:
  CHM13: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/input/human_CHM13/chm13.draft_v1.0_plusY"
  hg19: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/input/human_GRCh38/GRCh38_noalt_as"
  kraken2: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/input/kraken2_human_db"

motus:
  # motu database
  DBLoc: "/net/data.isilon/ag-saez/bq_kece/projects/saez/promise_lung_microbiome/input/db_mOTU"
  markerGenesCutoff: 2
  minReadLength: 45
  # -n for output sample name
  # -M  save the marker gene cluster (MGC) counts
  # -g marker genes cutoff
  # -l min read lenght



